runtime: python311

instance_class: F2

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  ENVIRONMENT: "production"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
